/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_ENUMS_PB_H_INCLUDED
#define PB_ENUMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _BaseState {
    BaseState_BASE_STATE_UNSPECIFIED = 0,
    BaseState_BASE_STATE_CHARGING = 10,
    BaseState_BASE_STATE_MONITORING = 42,
    BaseState_BASE_STATE_MONITORING_ALIAS = 42
} BaseState;

/* Helper constants for enums */
#define _BaseState_MIN BaseState_BASE_STATE_UNSPECIFIED
#define _BaseState_MAX BaseState_BASE_STATE_MONITORING_ALIAS
#define _BaseState_ARRAYSIZE ((BaseState)(BaseState_BASE_STATE_MONITORING_ALIAS+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
