# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enums.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enums.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x65nums.proto*\x80\x01\n\tBaseState\x12\x1a\n\x16\x42\x41SE_STATE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x42\x41SE_STATE_CHARGING\x10\n\x12\x19\n\x15\x42\x41SE_STATE_MONITORING\x10*\x12\x1f\n\x1b\x42\x41SE_STATE_MONITORING_ALIAS\x10*\x1a\x02\x10\x01\x62\x06proto3'
)

_BASESTATE = _descriptor.EnumDescriptor(
  name='BaseState',
  full_name='BaseState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASE_STATE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_STATE_CHARGING', index=1, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_STATE_MONITORING', index=2, number=42,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_STATE_MONITORING_ALIAS', index=3, number=42,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=b'\020\001',
  serialized_start=16,
  serialized_end=144,
)
_sym_db.RegisterEnumDescriptor(_BASESTATE)

BaseState = enum_type_wrapper.EnumTypeWrapper(_BASESTATE)
BASE_STATE_UNSPECIFIED = 0
BASE_STATE_CHARGING = 10
BASE_STATE_MONITORING = 42
BASE_STATE_MONITORING_ALIAS = 42


DESCRIPTOR.enum_types_by_name['BaseState'] = _BASESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_BASESTATE._options = None
# @@protoc_insertion_point(module_scope)
